
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class addBook extends javax.swing.JFrame {
    public Connection cn;
    public Statement st;
    /**
     * Creates new form addBook
     */
    public addBook() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/librarymanagement?zeroDateTimeBehavior=convertToNull","root","");
            st = cn.createStatement();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
        }
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rdgrpAddBook = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtBookID = new javax.swing.JTextField();
        txtTitle = new javax.swing.JTextField();
        cmbxCat = new javax.swing.JComboBox<>();
        txtFname = new javax.swing.JTextField();
        txtLname = new javax.swing.JTextField();
        txtMname = new javax.swing.JTextField();
        spnrCopies = new javax.swing.JSpinner();
        addBook = new javax.swing.JButton();
        rdbtnAddBook = new javax.swing.JRadioButton();
        rdbtAddCopy = new javax.swing.JRadioButton();
        btnAddCopy = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        spnrCopy2 = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 850));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 48)); // NOI18N
        jLabel1.setText("Add Book");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(610, 50, 250, 70);

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(1130, 700, 100, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Middle Name");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(440, 540, 160, 17);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Book ID");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(590, 130, 90, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Title");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(300, 280, 140, 22);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Category");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(300, 350, 140, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel6.setText("Author");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(300, 410, 140, 22);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Last Name");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(440, 440, 140, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("First Name");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(440, 490, 140, 17);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Copies");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(300, 590, 110, 22);

        txtBookID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtBookID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookIDActionPerformed(evt);
            }
        });
        txtBookID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtBookIDKeyTyped(evt);
            }
        });
        getContentPane().add(txtBookID);
        txtBookID.setBounds(720, 130, 200, 28);

        txtTitle.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTitle.setEnabled(false);
        txtTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitleActionPerformed(evt);
            }
        });
        getContentPane().add(txtTitle);
        txtTitle.setBounds(440, 280, 280, 28);

        cmbxCat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbxCat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fiction", "Non-Fiction", "Textbook", "Research" }));
        cmbxCat.setEnabled(false);
        getContentPane().add(cmbxCat);
        cmbxCat.setBounds(440, 350, 280, 28);

        txtFname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtFname.setEnabled(false);
        getContentPane().add(txtFname);
        txtFname.setBounds(440, 460, 280, 28);

        txtLname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtLname.setEnabled(false);
        getContentPane().add(txtLname);
        txtLname.setBounds(440, 410, 280, 28);

        txtMname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtMname.setEnabled(false);
        getContentPane().add(txtMname);
        txtMname.setBounds(440, 510, 280, 28);

        spnrCopies.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        spnrCopies.setEnabled(false);
        getContentPane().add(spnrCopies);
        spnrCopies.setBounds(440, 590, 110, 28);

        addBook.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addBook.setText("Add Book");
        addBook.setEnabled(false);
        addBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBookActionPerformed(evt);
            }
        });
        getContentPane().add(addBook);
        addBook.setBounds(360, 680, 150, 60);

        rdgrpAddBook.add(rdbtnAddBook);
        rdbtnAddBook.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdbtnAddBook.setText("Add Book");
        rdbtnAddBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtnAddBookActionPerformed(evt);
            }
        });
        getContentPane().add(rdbtnAddBook);
        rdbtnAddBook.setBounds(260, 220, 160, 31);

        rdgrpAddBook.add(rdbtAddCopy);
        rdbtAddCopy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdbtAddCopy.setText("Add Copy");
        rdbtAddCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdbtAddCopyActionPerformed(evt);
            }
        });
        getContentPane().add(rdbtAddCopy);
        rdbtAddCopy.setBounds(920, 220, 200, 31);

        btnAddCopy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAddCopy.setText("Add Copy");
        btnAddCopy.setEnabled(false);
        btnAddCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCopyActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddCopy);
        btnAddCopy.setBounds(1070, 340, 150, 60);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Copies");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(950, 280, 110, 22);

        spnrCopy2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        spnrCopy2.setEnabled(false);
        getContentPane().add(spnrCopy2);
        spnrCopy2.setBounds(1160, 270, 120, 28);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/istockphoto-1132077472-612x612 (2).jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 1500, 850);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        setVisible(false);
        new home().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtBookIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookIDActionPerformed

    private void txtTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitleActionPerformed

    private void txtBookIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBookIDKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtBookIDKeyTyped

    private void addBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBookActionPerformed
        
        String bookID = txtBookID.getText();
        String title = txtTitle.getText();
        String lname = txtLname.getText();
        String fname = txtFname.getText();
        String mname = txtMname.getText();
        int copies = (Integer) spnrCopies.getValue();
        String category = cmbxCat.getSelectedItem().toString();
        String name;
        
        name = lname +", "+fname+" "+mname;
        
        
        
        if (bookID.equals("") || title.equals("") || lname.equals("") || fname.equals("") || mname.equals("")){
            JOptionPane.showMessageDialog(null, "Fill all the necessary details");
        }
        else if(bookID.length()!=5){
            JOptionPane.showMessageDialog(null, "Invalid Book Number");
        }
        else if(copies < 1){
            JOptionPane.showMessageDialog(null, "Invalid Number of copies");
        }
        else{
            try{
                
                String search = "SELECT `BOOK ID` FROM `book` WHERE `BOOK ID` = "+bookID+";";
                ResultSet rs = st.executeQuery(search);
                
                if (rs.next()==false){
                    String sql1 = "INSERT INTO `book`(`BOOK ID`, `TITLE`, `AUTHOR`, `CATEGORY`, `COPIES`) VALUES ('"+ bookID +"', '"+ title +"', '"+ name +"', '"+ category +"', '"+ copies +"');";
                    st.executeUpdate(sql1);
                    JOptionPane.showMessageDialog(null, "Book Inserted");
                }
                else{
                    JOptionPane.showMessageDialog(null, "The book id is already inserted");
                }
                
            }
            catch (SQLException ex){
                Logger.getLogger(addStudent.class.getName()).log(Level.SEVERE,null,ex);
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_addBookActionPerformed

    private void rdbtnAddBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtnAddBookActionPerformed
        if (rdbtnAddBook.isSelected()){
            
            spnrCopy2.setValue(0);
            
            txtTitle.setEnabled(true);
            cmbxCat.setEnabled(true);
            txtLname.setEnabled(true);
            txtFname.setEnabled(true);
            txtMname.setEnabled(true);
            spnrCopies.setEnabled(true);
            addBook.setEnabled(true);
            spnrCopy2.setEnabled(false);
            btnAddCopy.setEnabled(false);
        }
    }//GEN-LAST:event_rdbtnAddBookActionPerformed

    private void rdbtAddCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdbtAddCopyActionPerformed
        if (rdbtAddCopy.isSelected()){
            
            txtTitle.setText("");
            cmbxCat.setSelectedItem("Fiction");
            txtLname.setText("");
            txtFname.setText("");
            txtMname.setText("");
            spnrCopies.setValue(0);
            
            txtTitle.setEnabled(false);
            cmbxCat.setEnabled(false);
            txtLname.setEnabled(false);
            txtFname.setEnabled(false);
            txtMname.setEnabled(false);
            spnrCopies.setEnabled(false);
            addBook.setEnabled(false);
            spnrCopy2.setEnabled(true);
            btnAddCopy.setEnabled(true);
        }
    }//GEN-LAST:event_rdbtAddCopyActionPerformed

    private void btnAddCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCopyActionPerformed
        String bookID = txtBookID.getText();
        int copies = (Integer) spnrCopy2.getValue();
        int orCopy = 0, newCopy;
        
        if(copies < 1){
            JOptionPane.showMessageDialog(null, "Invalid Number of copies");
        }
        else{
            try{
                
                String search = "SELECT `COPIES` FROM `book` WHERE `BOOK ID` = "+bookID+";";
                ResultSet rs = st.executeQuery(search);
                
                if (bookID.equals("")){
                    JOptionPane.showMessageDialog(null, "Please enter the book ID");
                }
                else if (rs.next()==false){
                    JOptionPane.showMessageDialog(null, "The book is not on the list");
                }
                else{
                    orCopy = rs.getInt("COPIES");
                    newCopy = orCopy + copies;
                    
                    String update = "UPDATE `book` SET `COPIES`='"+newCopy+"' WHERE `BOOK ID`="+bookID+";";
                    st.executeUpdate(update);
                    JOptionPane.showMessageDialog(null, "Copies successfuly added!");
                }
                
            }
            catch (SQLException ex){
                Logger.getLogger(addStudent.class.getName()).log(Level.SEVERE,null,ex);
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_btnAddCopyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBook;
    private javax.swing.JButton btnAddCopy;
    private javax.swing.JButton btnBack;
    private javax.swing.JComboBox<String> cmbxCat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rdbtAddCopy;
    private javax.swing.JRadioButton rdbtnAddBook;
    private javax.swing.ButtonGroup rdgrpAddBook;
    private javax.swing.JSpinner spnrCopies;
    private javax.swing.JSpinner spnrCopy2;
    private javax.swing.JTextField txtBookID;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtMname;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
