
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.*;
import java.io.IOException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class addStudent extends javax.swing.JFrame {
    public Connection cn;
    public Statement st;
    /**
     * Creates new form addStudent
     */
    public addStudent() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/librarymanagement?zeroDateTimeBehavior=convertToNull","root","");
            st = cn.createStatement();
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
        }
        
        for(int i = 1800; i<2022;i++){
            cmbxYear.addItem(String.valueOf(i));
        }
        
        cmbxYear.setSelectedItem("2021");
        
        rbtnMale.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrpGender = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMname = new javax.swing.JTextField();
        txtLname = new javax.swing.JTextField();
        txtFname = new javax.swing.JTextField();
        rbtnMale = new javax.swing.JRadioButton();
        rbtnFemale = new javax.swing.JRadioButton();
        rbtnNon = new javax.swing.JRadioButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        txtStudentID = new javax.swing.JTextField();
        txtAdd4 = new javax.swing.JTextField();
        txtAdd1 = new javax.swing.JTextField();
        txtAdd2 = new javax.swing.JTextField();
        txtAdd3 = new javax.swing.JTextField();
        cmbxMonth = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cmbxSYear = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cmbxCourse = new javax.swing.JComboBox<>();
        cmbxDate = new javax.swing.JComboBox<>();
        cmbxYear = new javax.swing.JComboBox<>();
        addStudent = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 850));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 48)); // NOI18N
        jLabel1.setText("Add Student");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(590, 30, 330, 80);

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(840, 681, 100, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Student ID");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(550, 160, 110, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Name");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(300, 240, 70, 22);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Last Name");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(400, 270, 90, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("Gender");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(300, 330, 100, 22);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("First Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(620, 270, 100, 17);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Middle Name");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(900, 270, 130, 17);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel8.setText("Address");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(300, 490, 100, 22);

        txtMname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtMname);
        txtMname.setBounds(900, 240, 200, 28);

        txtLname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtLname);
        txtLname.setBounds(400, 240, 200, 28);

        txtFname.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtFname);
        txtFname.setBounds(620, 240, 260, 28);

        btngrpGender.add(rbtnMale);
        rbtnMale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbtnMale.setText("Male");
        getContentPane().add(rbtnMale);
        rbtnMale.setBounds(410, 330, 90, 31);

        btngrpGender.add(rbtnFemale);
        rbtnFemale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbtnFemale.setText("Female");
        getContentPane().add(rbtnFemale);
        rbtnFemale.setBounds(520, 330, 110, 31);

        btngrpGender.add(rbtnNon);
        rbtnNon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rbtnNon.setText("Non-binary");
        getContentPane().add(rbtnNon);
        rbtnNon.setBounds(660, 330, 140, 31);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel15.setText("Birthday");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(300, 410, 100, 22);

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Street/Barangay");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(400, 520, 140, 22);

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("City/Municipality");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(620, 520, 160, 22);

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("State/Province");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(840, 520, 160, 22);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("ZIP Code");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(1060, 520, 160, 22);

        txtStudentID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtStudentID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStudentIDKeyTyped(evt);
            }
        });
        getContentPane().add(txtStudentID);
        txtStudentID.setBounds(680, 160, 200, 30);

        txtAdd4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtAdd4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAdd4KeyTyped(evt);
            }
        });
        getContentPane().add(txtAdd4);
        txtAdd4.setBounds(1060, 490, 200, 28);

        txtAdd1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtAdd1);
        txtAdd1.setBounds(400, 490, 200, 28);

        txtAdd2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtAdd2);
        txtAdd2.setBounds(620, 490, 200, 28);

        txtAdd3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(txtAdd3);
        txtAdd3.setBounds(840, 490, 200, 28);

        cmbxMonth.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbxMonth.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sept", "Oct", "Nov", "Dec" }));
        cmbxMonth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxMonthActionPerformed(evt);
            }
        });
        getContentPane().add(cmbxMonth);
        cmbxMonth.setBounds(540, 410, 90, 28);

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel9.setText("Year");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(300, 580, 60, 22);

        cmbxSYear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbxSYear.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        getContentPane().add(cmbxSYear);
        cmbxSYear.setBounds(400, 580, 200, 28);

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Course");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(750, 580, 70, 22);

        cmbxCourse.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbxCourse.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSIT", "BSCS", "BSCE" }));
        getContentPane().add(cmbxCourse);
        cmbxCourse.setBounds(830, 580, 200, 28);

        cmbxDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbxDate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxDateActionPerformed(evt);
            }
        });
        getContentPane().add(cmbxDate);
        cmbxDate.setBounds(670, 410, 90, 28);

        cmbxYear.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbxYear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxYearActionPerformed(evt);
            }
        });
        getContentPane().add(cmbxYear);
        cmbxYear.setBounds(400, 410, 100, 28);

        addStudent.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addStudent.setText("Add Student");
        addStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentActionPerformed(evt);
            }
        });
        getContentPane().add(addStudent);
        addStudent.setBounds(620, 670, 200, 60);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/istockphoto-1132077472-612x612 (2).jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 1500, 850);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        setVisible(false);
        new home().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtStudentIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStudentIDKeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtStudentIDKeyTyped

    private void cmbxMonthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxMonthActionPerformed
        String month = cmbxMonth.getSelectedItem().toString();
        String year = cmbxYear.getSelectedItem().toString();
        int intYear = Integer.parseInt(year);
        
        cmbxDate.removeAllItems();
        
        if(month.equals("Jan") || month.equals("Mar") || month.equals("May") || month.equals("Jul") || month.equals("Aug") || month.equals("Oct") || month.equals("Dec") ){
            for (int i=1; i<=31; i++){
                cmbxDate.addItem(String.valueOf(i));
            }
        }
        else if(month.equals("Apr") || month.equals("Jun") || month.equals("Sept") || month.equals("Nov")){
            for (int i=1; i<=30; i++){
                cmbxDate.addItem(String.valueOf(i));
            }
        }
        else if(month.equals("Feb") && intYear%4==0){
            for (int i=1; i<=29; i++){
                cmbxDate.addItem(String.valueOf(i));
            }
        }
        else if(month.equals("Feb") && intYear%4>=1){
            for (int i=1; i<=28; i++){
                cmbxDate.addItem(String.valueOf(i));
            }
        }
    }//GEN-LAST:event_cmbxMonthActionPerformed

    private void cmbxDateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxDateActionPerformed
    }//GEN-LAST:event_cmbxDateActionPerformed

    private void cmbxYearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxYearActionPerformed
        String month = cmbxMonth.getSelectedItem().toString();
        String year = cmbxYear.getSelectedItem().toString();
        int intYear = Integer.parseInt(year);
        
        cmbxDate.removeAllItems();
        
        if(month.equals("Jan") || month.equals("Mar") || month.equals("May") || month.equals("Jul") || month.equals("Aug") || month.equals("Oct") || month.equals("Dec") ){
            for (int i=1; i<=31; i++){
                cmbxDate.addItem(String.valueOf(i));
            }
        }
        else if(month.equals("Apr") || month.equals("Jun") || month.equals("Sept") || month.equals("Nov")){
            for (int i=1; i<=30; i++){
                cmbxDate.addItem(String.valueOf(i));
            }
        }
        else if(month.equals("Feb") && intYear%4==0){
            for (int i=1; i<=29; i++){
                cmbxDate.addItem(String.valueOf(i));
            }
        }
        else if(month.equals("Feb") && intYear%4>=1){
            for (int i=1; i<=28; i++){
                cmbxDate.addItem(String.valueOf(i));
            }
        }
    }//GEN-LAST:event_cmbxYearActionPerformed

    private void txtAdd4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAdd4KeyTyped
        char c = evt.getKeyChar();
        
        if(!Character.isDigit(c)){
            evt.consume();
        }
    }//GEN-LAST:event_txtAdd4KeyTyped

    private void addStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentActionPerformed
        // TODO add your handling code here:
        String studID = txtStudentID.getText();
        String lname = txtLname.getText();
        String fname = txtFname.getText();
        String mname = txtMname.getText();
        String month = cmbxMonth.getSelectedItem().toString();
        String date = cmbxDate.getSelectedItem().toString();
        String year = cmbxYear.getSelectedItem().toString();
        String add1 = txtAdd1.getText();
        String add2 = txtAdd2.getText();
        String add3 = txtAdd3.getText();
        String add4 = txtAdd4.getText();
        String gender, address, birthday;
        String syear = cmbxSYear.getSelectedItem().toString();
        String course = cmbxCourse.getSelectedItem().toString();;
        String search;        
        
        if(studID.equals("") || lname.equals("") || fname.equals("") || mname.equals("") || add1.equals("") || add2.equals("") || add3.equals("") || add4.equals("")){
            JOptionPane.showMessageDialog(null, "Fill all the necessary details");
        }
        else if(studID.length()!=5){
            JOptionPane.showMessageDialog(null, "Invalid Student Number");
        }
        else if(add4.length()!=4){
            JOptionPane.showMessageDialog(null, "Invalid Zip Code");
        }
        else{
            if(rbtnMale.isSelected()){
                gender = "Male";
            }
            else if(rbtnFemale.isSelected()){
                gender = "Female";
            }
            else{
                gender = "Non-binary";
            }
            
            address = add1 + " " + add2 + " " + add3 + " " + add4;
            birthday = month + ". " + date + ", " + year;
            
            try{
                
                search = "SELECT `STUDENT ID` FROM `student` WHERE `STUDENT ID` = "+studID+";";
                ResultSet rs = st.executeQuery(search);
                
                if (rs.next()==false){
                    String sql1 = "INSERT INTO `student`(`STUDENT ID`, `LAST NAME`, `FIRST NAME`, `MIDDLE NAME`, `GENDER`, `BIRTHDAY`, `ADDRESS`, `YEAR LEVEL`, `COURSE`)" +" VALUES ('"+ studID +"', '"+ lname +"', '"+ fname +"', '"+ mname +"', '"+ gender +"', '"+ birthday +"', '"+ address +"', '"+ syear +"', '"+ course +"');";
                    st.executeUpdate(sql1);
                    JOptionPane.showMessageDialog(null, "Student Inserted");
                }
                else{
                    JOptionPane.showMessageDialog(null, "This student is already registered.");
                }
                
            }
            catch (SQLException ex){
                Logger.getLogger(addStudent.class.getName()).log(Level.SEVERE,null,ex);
                JOptionPane.showMessageDialog(null, ex);
            }
            
        }
    }//GEN-LAST:event_addStudentActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addStudent;
    private javax.swing.JButton btnBack;
    private javax.swing.ButtonGroup btngrpGender;
    private javax.swing.JComboBox<String> cmbxCourse;
    private javax.swing.JComboBox<String> cmbxDate;
    private javax.swing.JComboBox<String> cmbxMonth;
    private javax.swing.JComboBox<String> cmbxSYear;
    private javax.swing.JComboBox<String> cmbxYear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton rbtnFemale;
    private javax.swing.JRadioButton rbtnMale;
    private javax.swing.JRadioButton rbtnNon;
    private javax.swing.JTextField txtAdd1;
    private javax.swing.JTextField txtAdd2;
    private javax.swing.JTextField txtAdd3;
    private javax.swing.JTextField txtAdd4;
    private javax.swing.JTextField txtFname;
    private javax.swing.JTextField txtLname;
    private javax.swing.JTextField txtMname;
    private javax.swing.JTextField txtStudentID;
    // End of variables declaration//GEN-END:variables

}
