
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ACER
 */
public class searchBook extends javax.swing.JFrame {
    public Connection cn;
    public Statement st;
    /**
     * Creates new form searchBook
     */
    public searchBook() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        try{
            Class.forName("com.mysql.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/librarymanagement?zeroDateTimeBehavior=convertToNull","root","");
            st = cn.createStatement();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbxSearch = new javax.swing.JComboBox<>();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 850));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 3, 48)); // NOI18N
        jLabel1.setText("Search Book");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(600, 30, 300, 70);

        btnBack.setText("Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack);
        btnBack.setBounds(1280, 710, 100, 40);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Search by");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(560, 120, 120, 22);

        cmbxSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbxSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Book ID", "Title", "Category", "Author" }));
        cmbxSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbxSearchActionPerformed(evt);
            }
        });
        getContentPane().add(cmbxSearch);
        cmbxSearch.setBounds(720, 120, 230, 28);

        lblSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblSearch.setText("Enter Book ID: ");
        getContentPane().add(lblSearch);
        lblSearch.setBounds(560, 170, 130, 22);

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSearchKeyTyped(evt);
            }
        });
        getContentPane().add(txtSearch);
        txtSearch.setBounds(720, 170, 230, 28);

        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        getContentPane().add(btnSearch);
        btnSearch.setBounds(680, 220, 140, 50);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Book ID", "Title", "Author", "Category", "Copies"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(350, 300, 820, 410);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/istockphoto-1132077472-612x612 (2).jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 1500, 850);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        setVisible(false);
        new home().setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbxSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbxSearchActionPerformed
        String search = cmbxSearch.getSelectedItem().toString();
        
        lblSearch.setText("Enter "+search+":");
        txtSearch.setText("");
    }//GEN-LAST:event_cmbxSearchActionPerformed

    private void txtSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyTyped
        String search = cmbxSearch.getSelectedItem().toString();
        
        if(search.equals("Book ID")){
            char c = evt.getKeyChar();
        
            if(!Character.isDigit(c)){
                evt.consume();
        }
        }
    }//GEN-LAST:event_txtSearchKeyTyped

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String search = txtSearch.getText();
        String choice = cmbxSearch.getSelectedItem().toString();
        DefaultTableModel tblModel = (DefaultTableModel)jTable1.getModel();
        ResultSet rs = null;
        String ssql = "";
        
        tblModel.setRowCount(0);
        
        if(search.equals("")){
                JOptionPane.showMessageDialog(null, "Fill the necessary details");
            }
        
        else if(choice.equals("Book ID") && search.length()!=5){
                JOptionPane.showMessageDialog(null, "Invalid Student Number");
                txtSearch.setText("");
        }
        else{
        try{
        
            if(choice.equals("Book ID")){
                ssql = "SELECT `BOOK ID`,`TITLE`,`AUTHOR`,`CATEGORY`,`COPIES` FROM `book` WHERE `BOOK ID`="+search+";";
            }
            else if(choice.equals("Title")){
                ssql = "SELECT `BOOK ID`,`TITLE`,`AUTHOR`,`CATEGORY`,`COPIES` FROM `book` WHERE `TITLE`='"+search+"';";
            }
            else if(choice.equals("Category")){
                ssql = "SELECT `BOOK ID`,`TITLE`,`AUTHOR`,`CATEGORY`,`COPIES` FROM `book` WHERE `CATEGORY`='"+search+"';";
            }
            else if(choice.equals("Author")){
                ssql = "SELECT `BOOK ID`,`TITLE`,`AUTHOR`,`CATEGORY`,`COPIES` FROM `book` WHERE `AUTHOR`='"+search+"';";
            }
            
            rs = st.executeQuery(ssql);
            
            if(rs.next()==false){
                JOptionPane.showMessageDialog(null, "No Data was found");
            }
            else{
                String id = rs.getString("BOOK ID");
                String title = rs.getString("TITLE");
                String author = rs.getString("AUTHOR");
                String category = rs.getString("CATEGORY");
                String copy = rs.getString("COPIES");
                    
                Object tbData[] = {id, title, author, category, copy};
                tblModel.addRow(tbData);
                
                while(rs.next()){
                    id = rs.getString("BOOK ID");
                    title = rs.getString("TITLE");
                    author = rs.getString("AUTHOR");
                    category = rs.getString("CATEGORY");
                    copy = rs.getString("COPIES");
                    
                    Object tbData2[] = {id, title, author, category, copy};
                    tblModel.addRow(tbData2);
                }
                
            }
        }
        catch (SQLException ex){
                Logger.getLogger(searchStudent.class.getName()).log(Level.SEVERE,null,ex);
                JOptionPane.showMessageDialog(null, ex);
        }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(searchBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(searchBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(searchBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(searchBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new searchBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbxSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
